# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/asgei/Desktop/RSA/intergration_kit_RSA/RSA_soc/boards/ip/rsa_soc_auto_pc_0/rsa_soc_auto_pc_0.xci
# IP: The module: 'rsa_soc_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/asgei/Desktop/RSA/intergration_kit_RSA/RSA_soc/boards/ip/rsa_soc_auto_pc_0/rsa_soc_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rsa_soc_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/asgei/Desktop/RSA/intergration_kit_RSA/RSA_soc/boards/ip/rsa_soc_auto_pc_0/rsa_soc_auto_pc_0.xci
# IP: The module: 'rsa_soc_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/asgei/Desktop/RSA/intergration_kit_RSA/RSA_soc/boards/ip/rsa_soc_auto_pc_0/rsa_soc_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rsa_soc_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
