@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Wed Nov 20 10:45:52 +0100 2019
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim RSA_accelerator_tb_behav -key {Behavioral:sim_1:Functional:RSA_accelerator_tb} -tclbatch RSA_accelerator_tb.tcl -view C:/Users/asgei/Desktop/manuals/RSA/intergration_kit_RSA/RSA_accelerator/RSA_accelerator/RSA_accelerator_tb_behav.wcfg -log simulate.log"
call xsim  RSA_accelerator_tb_behav -key {Behavioral:sim_1:Functional:RSA_accelerator_tb} -tclbatch RSA_accelerator_tb.tcl -view C:/Users/asgei/Desktop/manuals/RSA/intergration_kit_RSA/RSA_accelerator/RSA_accelerator/RSA_accelerator_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
